import { betterAuth } from "better-auth";
import { findLibrary, resolveIdentity, type LibraryRow } from "./identity.ts";

// Generated by `wrangler types`; do not duplicate binding declarations here.
export type Env = Cloudflare.Env;

export function registrationClosed(env: Env): boolean {
  return String(env.REGISTRATION_MODE) === "closed";
}

function stripGoogleTokens<T extends Record<string, unknown>>(account: T): T {
  return {
    ...account,
    accessToken: null,
    refreshToken: null,
    idToken: null,
    accessTokenExpiresAt: null,
    refreshTokenExpiresAt: null,
  };
}

export function createAuth(env: Env) {
  return betterAuth({
    appName: "Locus",
    baseURL: env.BETTER_AUTH_URL,
    secret: env.BETTER_AUTH_SECRET,
    database: env.DB,
    trustedOrigins: [env.BETTER_AUTH_URL],
    account: {
      identityStrategy: "provider-id",
      accountLinking: { enabled: false },
    },
    databaseHooks: {
      account: {
        create: {
          before: async (account) => ({ data: stripGoogleTokens(account) }),
        },
        update: {
          before: async (account) => ({ data: stripGoogleTokens(account) }),
        },
      },
    },
    socialProviders: {
      google: {
        clientId: env.GOOGLE_CLIENT_ID,
        clientSecret: env.GOOGLE_CLIENT_SECRET,
        disableSignUp: registrationClosed(env),
      },
    },
    onAPIError: {
      errorURL: env.BETTER_AUTH_URL,
    },
    advanced: {
      useSecureCookies: env.BETTER_AUTH_URL.startsWith("https://"),
      database: {
        generateId: () => crypto.randomUUID(),
      },
    },
  });
}

export async function ensureLibrary(env: Env, userId: string, displayName: string): Promise<LibraryRow> {
  const existing = await findLibrary(env, userId);
  if (existing) return existing;

  const libraryId = crypto.randomUUID();
  const now = Date.now();
  const name = displayName ? `${displayName}'s Library` : "My Library";

  try {
    await env.DB.batch([
      env.DB.prepare(
        "INSERT INTO libraries (id, owner_user_id, name, created_at, updated_at) VALUES (?, ?, ?, ?, ?)",
      ).bind(libraryId, userId, name, now, now),
      env.DB.prepare(
        "INSERT INTO library_memberships (library_id, user_id, role, created_at) VALUES (?, ?, 'owner', ?)",
      ).bind(libraryId, userId, now),
    ]);
  } catch {
    // Concurrent first requests may race. Uniqueness constraints choose the
    // winner; re-reading gives both requests the same Library.
  }

  const created = await findLibrary(env, userId);
  if (!created) throw new Error("Could not provision a Library for this user");
  return created;
}

async function ensureAccess(env: Env, user: { id: string; email: string }): Promise<"active" | "disabled"> {
  const existing = await env.DB.prepare("SELECT status FROM user_access WHERE user_id = ?")
    .bind(user.id)
    .first<{ status: "active" | "disabled" }>();
  if (existing) return existing.status;

  try {
    await env.DB.prepare(
      "INSERT INTO user_access (user_id, email, status, created_at) VALUES (?, ?, 'active', ?)",
    )
      .bind(user.id, user.email.toLowerCase(), Date.now())
      .run();
    return "active";
  } catch {
    const raced = await env.DB.prepare("SELECT status FROM user_access WHERE user_id = ?")
      .bind(user.id)
      .first<{ status: "active" | "disabled" }>();
    if (raced) return raced.status;
    throw new Error("Could not provision access for this user");
  }
}

function libraryIdFromPath(pathname: string): string | null {
  const match = pathname.match(/^\/api\/libraries\/([^/]+)$/);
  if (!match) return null;
  try {
    return decodeURIComponent(match[1]);
  } catch {
    return null;
  }
}

function isMutation(method: string): boolean {
  return method !== "GET" && method !== "HEAD" && method !== "OPTIONS";
}

function bytesToBase64Url(bytes: ArrayBuffer): string {
  const bin = String.fromCharCode(...new Uint8Array(bytes));
  return btoa(bin).replaceAll("+", "-").replaceAll("/", "_").replaceAll("=", "");
}

async function hmac(secret: string, value: string): Promise<string> {
  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  );
  const sig = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(value));
  return bytesToBase64Url(sig);
}

export async function csrfToken(sessionId: string, secret: string): Promise<string> {
  if (!secret || !sessionId) return "";
  return hmac(secret, sessionId);
}

async function timingSafeEqual(a: string, b: string): Promise<boolean> {
  const encoder = new TextEncoder();
  const [left, right] = await Promise.all([
    crypto.subtle.digest("SHA-256", encoder.encode(a)),
    crypto.subtle.digest("SHA-256", encoder.encode(b)),
  ]);
  const leftBytes = new Uint8Array(left);
  const rightBytes = new Uint8Array(right);
  let difference = 0;
  for (let index = 0; index < leftBytes.length; index++) {
    difference |= leftBytes[index] ^ rightBytes[index];
  }
  return difference === 0;
}

async function validCsrf(sessionId: string, token: string | null, secret: string): Promise<boolean> {
  if (!token || !secret) return false;
  const expected = await csrfToken(sessionId, secret);
  return expected.length > 0 && (await timingSafeEqual(token, expected));
}

async function requireMutationProtection(
  request: Request,
  env: Env,
  sessionId: string,
): Promise<Response | null> {
  if (request.headers.get("origin") !== env.BETTER_AUTH_URL) {
    return json({ error: "Forbidden" }, 403);
  }
  const token = request.headers.get("x-csrf-token");
  if (!(await validCsrf(sessionId, token, env.CSRF_SECRET))) {
    return json({ error: "Forbidden" }, 403);
  }
  return null;
}

export function redact(value: string): string {
  return value
    .replace(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi, "[redacted]")
    .replace(/((?:set-)?cookie\s*[:=]\s*)[^;\n]+/gi, "$1[redacted]")
    .replace(
      /\b(better-auth\.session_token|access_token|refresh_token|id_token|authorization|code|token)=([^&\s;]+)/gi,
      "$1=[redacted]",
    );
}

type LogLevel = "info" | "error";

export interface LogEvent {
  level: LogLevel;
  event: string;
  requestId: string;
  method: string;
  path: string;
  status: number;
  detail?: string;
  timestamp?: string;
}

export function logEvent(
  input: LogEvent,
  emit?: (line: string) => void,
): void {
  const record = {
    timestamp: input.timestamp ?? new Date().toISOString(),
    level: input.level,
    event: redact(input.event),
    requestId: redact(input.requestId),
    method: redact(input.method),
    path: redact(input.path.split("?", 1)[0]),
    status: input.status,
    ...(input.detail ? { detail: redact(input.detail) } : {}),
  };
  const line = JSON.stringify(record);
  if (emit) emit(line);
  else if (input.level === "error") console.error(line);
  else console.log(line);
}

export function mayLogRequest(request: Request, url = new URL(request.url)): boolean {
  return (
    url.search.length === 0 &&
    !request.headers.has("cookie") &&
    !request.headers.has("authorization")
  );
}

function clientRateLimitKey(request: Request, scope: string): string {
  const client = request.headers.get("cf-connecting-ip") ?? "unknown";
  return `${scope}:${client}`;
}

async function enforceRateLimit(
  request: Request,
  limiter: RateLimit,
  scope: string,
): Promise<Response | null> {
  const outcome = await limiter.limit({ key: clientRateLimitKey(request, scope) });
  if (outcome.success) return null;
  return json(
    { error: "Too many requests" },
    429,
    { "retry-after": "60" },
  );
}

function authRateLimitScope(request: Request, pathname: string): string | null {
  if (request.method === "POST" && pathname === "/api/auth/sign-in/social") return "sign-in";
  if (pathname === "/api/auth/callback/google") return "google-callback";
  return null;
}

async function rejectedSessionResponse(
  request: Request,
  env: Env,
  response: Response,
): Promise<Response> {
  const limited = await enforceRateLimit(request, env.REJECTED_SESSION_RATE_LIMITER, "private-rejection");
  return limited ?? response;
}

export function applySecurityHeaders(response: Response, requestUrl: URL): Response {
  const headers = new Headers(response.headers);
  const hashedAsset = response.ok && requestUrl.pathname.startsWith("/assets/");
  headers.set("cache-control", hashedAsset ? "public, max-age=31536000, immutable" : "no-store");
  headers.set(
    "content-security-policy",
    "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' https: data:; base-uri 'none'; form-action 'self'; frame-ancestors 'none'",
  );
  headers.set("permissions-policy", "camera=(), geolocation=(), microphone=()");
  headers.set("referrer-policy", "no-referrer");
  headers.set("x-content-type-options", "nosniff");
  headers.set("x-frame-options", "DENY");
  if (requestUrl.protocol === "https:") {
    headers.set("strict-transport-security", "max-age=31536000; includeSubDomains");
  } else {
    headers.delete("strict-transport-security");
  }
  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}

function json(value: unknown, status = 200, headers?: HeadersInit): Response {
  const responseHeaders = new Headers(headers);
  responseHeaders.set("cache-control", "no-store");
  return Response.json(value, {
    status,
    headers: responseHeaders,
  });
}

function expiresAt(value: Date | string): string {
  return value instanceof Date ? value.toISOString() : String(value);
}

async function route(request: Request, env: Env): Promise<Response> {
  const url = new URL(request.url);
  const auth = createAuth(env);

  if (url.pathname.startsWith("/api/auth/")) {
    const scope = authRateLimitScope(request, url.pathname);
    if (scope) {
      const limited = await enforceRateLimit(request, env.AUTH_RATE_LIMITER, scope);
      if (limited) return limited;
    }
    return auth.handler(request);
  }

  if (request.method === "GET" && url.pathname === "/api/health") {
    return json({ ok: true });
  }

  if (request.method === "GET" && url.pathname === "/api/session") {
    const session = await auth.api.getSession({ headers: request.headers });
    if (!session) {
      return rejectedSessionResponse(request, env, json({ error: "Unauthorized" }, 401));
    }
    const access = await ensureAccess(env, session.user);
    if (access !== "active") {
      return rejectedSessionResponse(request, env, json({ error: "Forbidden" }, 403));
    }
    const library = await ensureLibrary(env, session.user.id, session.user.name);
    const token = await csrfToken(session.session.id, env.CSRF_SECRET);
    return json({
      user: {
        id: session.user.id,
        name: session.user.name,
        email: session.user.email,
        image: session.user.image ?? null,
      },
      session: {
        expiresAt: expiresAt(session.session.expiresAt),
      },
      library: {
        id: library.id,
        name: library.name,
        role: library.role,
      },
      csrfToken: token,
    });
  }

  const libraryId = libraryIdFromPath(url.pathname);
  if (libraryId && (request.method === "GET" || request.method === "POST")) {
    const session = await auth.api.getSession({ headers: request.headers });
    const resolved = await resolveIdentity(env, session);
    if (!resolved.ok) {
      return rejectedSessionResponse(request, env, json({ error: resolved.error }, resolved.status));
    }
    if (isMutation(request.method)) {
      const blocked = await requireMutationProtection(request, env, resolved.identity.sessionId);
      if (blocked) return blocked;
    }
    if (libraryId !== resolved.identity.libraryId) {
      return json({ error: "Not found" }, 404);
    }
    return json({
      id: resolved.library.id,
      name: resolved.library.name,
      role: resolved.library.role,
    });
  }

  if (url.pathname.startsWith("/api/")) {
    return json({ error: "Not found" }, 404);
  }
  return env.ASSETS.fetch(request);
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);
    const requestId = request.headers.get("cf-ray") ?? crypto.randomUUID();
    try {
      const response = applySecurityHeaders(await route(request, env), url);
      if (mayLogRequest(request, url)) {
        logEvent({
          level: "info",
          event: "request.complete",
          requestId,
          method: request.method,
          path: url.pathname,
          status: response.status,
        });
      }
      return response;
    } catch {
      const response = applySecurityHeaders(json({ error: "Internal server error" }, 500), url);
      if (mayLogRequest(request, url)) {
        logEvent({
          level: "error",
          event: "request.failed",
          requestId,
          method: request.method,
          path: url.pathname,
          status: 500,
          detail: "Unhandled Worker error",
        });
      }
      return response;
    }
  },
} satisfies ExportedHandler<Env>;
