import { betterAuth } from "better-auth";
import { RejectedPayload } from "../../core/sanitize.ts";
import { parseBatch, parseFinish, parseSession } from "../../packages/protocol/validate.ts";
import {
  AtlasConflict,
  acceptSuggestion,
  changePlace,
  createPlace,
  getAtlasProjection,
  leaveUnresolved,
  markMultiple,
  markNotAtlas,
  searchPlaces,
  setExactPlace,
  setHomeBase,
} from "./atlas.ts";
import {
  issueLibraryCapability,
  libraryCapabilityUsable,
  listLibraryCapabilities,
  lookupLibraryCapability,
  revokeLibraryCapability,
} from "./capabilities.ts";
import {
  MissingResource,
  addItemNote,
  addItemTag,
  addItemToCollection,
  commitIntake,
  createLibraryCollection,
  getLibraryItem,
  itemCounts,
  listItemsPage,
  listLibraryOrg,
  previewIntake,
  removeItemFromCollection,
  removeItemTag,
  setItemStatus,
  type ItemListFilter,
} from "./desk.ts";
import {
  commitIntakeBatch,
  commitReviewedDrafts,
  createIntakeTag,
  getIntakeContext,
  preparePresentedDrafts,
  searchLibrary,
} from "./intake.ts";
import { handleLibraryMcp } from "./mcp.ts";
import { findLibrary, resolveIdentity, type LibraryRow, type RequestIdentity } from "./identity.ts";
import { frameCheck, getLinkPreview } from "./preview.ts";
import { buildSummary, proseUnavailableMessage, type SummaryScope } from "./summaries.ts";
import { findSharedSnapshot } from "./trips.ts";
import { renderShareHtml } from "../../core/trip-share-html.ts";
import {
  KitchenConflict,
  KitchenUnavailable,
  addTonight,
  applyTonightChanges,
  clearTonight,
  getKitchenIndex,
  getKitchenItem,
  getTonight,
  getTonightView,
  kitchenAiStatus,
  makeCookable,
  putRecipeDocument,
  removeRecipeDocument,
  removeTonight,
  reorderTonight,
} from "./kitchen.ts";
import {
  drainReading,
  getAgentReadingDocument,
  getReadingDocument,
  listReadingDocuments,
  listReadingDocumentsForAgent,
  reconcileItem,
  removeReadingDocument,
  retryReadingDocument,
  undoRemoveReadingDocument,
  updateReadingProgress,
  type ReadingListQuery,
  type ReadingSort,
  type ReadingView,
} from "./reading.ts";
import {
  CaptureAuthorizationError,
  importJsonl,
  ingestBatch,
  knownCompleteIds,
  lookupToken,
  startSession,
  finishSession,
  type CaptureToken,
} from "./capture.ts";
import {
  CaptureConflict,
  ExtensionRequired,
  beginCapture,
  cancelCapture,
  disconnectSource,
  finishCaptureJob,
  getAccessibleJob,
  heartbeat,
  jobDeliveryView,
  jobForTokenId,
  jobStatusView,
  pairExtension,
  retargetJobs,
  setJobProgress,
  sourcesOverview,
  touchJobLease,
  waitJob,
} from "./sources.ts";
import {
  ReviewIntentError,
  TripConflict,
  applyTripChanges,
  archiveTrip,
  armReviewIntent,
  createTrip,
  deleteTrip,
  dismissTripAdvisory,
  duplicateTrip,
  getShareState,
  getTrip,
  getTripHistory,
  listTrips,
  previewShareSnapshot,
  publishShareSnapshot,
  recordAgentReview,
  redoTripChanges,
  removeTripInference,
  renameTrip,
  restoreTrip,
  revokeShareSnapshot,
  searchTripSources,
  undoTripChanges,
  updateTripSetup,
} from "./trips.ts";

// Generated by `wrangler types`; do not duplicate binding declarations here.
// Static Assets stay top-level in wrangler.jsonc; staging `wrangler types --env` omits ASSETS.
export type Env = Cloudflare.Env & { ASSETS: Fetcher };

export function registrationClosed(env: Env): boolean {
  return String(env.REGISTRATION_MODE) === "closed";
}

function stripGoogleTokens<T extends Record<string, unknown>>(account: T): T {
  return {
    ...account,
    accessToken: null,
    refreshToken: null,
    idToken: null,
    accessTokenExpiresAt: null,
    refreshTokenExpiresAt: null,
  };
}

export function createAuth(env: Env) {
  return betterAuth({
    appName: "Locus",
    baseURL: env.BETTER_AUTH_URL,
    secret: env.BETTER_AUTH_SECRET,
    database: env.DB,
    trustedOrigins: [env.BETTER_AUTH_URL],
    account: {
      identityStrategy: "provider-id",
      accountLinking: { enabled: false },
    },
    databaseHooks: {
      account: {
        create: {
          before: async (account) => ({ data: stripGoogleTokens(account) }),
        },
        update: {
          before: async (account) => ({ data: stripGoogleTokens(account) }),
        },
      },
    },
    socialProviders: {
      google: {
        clientId: env.GOOGLE_CLIENT_ID,
        clientSecret: env.GOOGLE_CLIENT_SECRET,
        disableSignUp: registrationClosed(env),
      },
    },
    onAPIError: {
      errorURL: env.BETTER_AUTH_URL,
    },
    advanced: {
      useSecureCookies: env.BETTER_AUTH_URL.startsWith("https://"),
      database: {
        generateId: () => crypto.randomUUID(),
      },
    },
  });
}

export async function ensureLibrary(env: Env, userId: string, displayName: string): Promise<LibraryRow> {
  const existing = await findLibrary(env, userId);
  if (existing) return existing;

  const libraryId = crypto.randomUUID();
  const now = Date.now();
  const name = displayName ? `${displayName}'s Library` : "My Library";

  try {
    await env.DB.batch([
      env.DB.prepare(
        "INSERT INTO libraries (id, owner_user_id, name, created_at, updated_at) VALUES (?, ?, ?, ?, ?)",
      ).bind(libraryId, userId, name, now, now),
      env.DB.prepare(
        "INSERT INTO library_memberships (library_id, user_id, role, created_at) VALUES (?, ?, 'owner', ?)",
      ).bind(libraryId, userId, now),
    ]);
  } catch {
    // Concurrent first requests may race. Uniqueness constraints choose the
    // winner; re-reading gives both requests the same Library.
  }

  const created = await findLibrary(env, userId);
  if (!created) throw new Error("Could not provision a Library for this user");
  return created;
}

async function ensureAccess(env: Env, user: { id: string; email: string }): Promise<"active" | "disabled"> {
  const existing = await env.DB.prepare("SELECT status FROM user_access WHERE user_id = ?")
    .bind(user.id)
    .first<{ status: "active" | "disabled" }>();
  if (existing) return existing.status;

  try {
    await env.DB.prepare(
      "INSERT INTO user_access (user_id, email, status, created_at) VALUES (?, ?, 'active', ?)",
    )
      .bind(user.id, user.email.toLowerCase(), Date.now())
      .run();
    return "active";
  } catch {
    const raced = await env.DB.prepare("SELECT status FROM user_access WHERE user_id = ?")
      .bind(user.id)
      .first<{ status: "active" | "disabled" }>();
    if (raced) return raced.status;
    throw new Error("Could not provision access for this user");
  }
}

function libraryIdFromPath(pathname: string): string | null {
  const match = pathname.match(/^\/api\/libraries\/([^/]+)$/);
  if (!match) return null;
  try {
    return decodeURIComponent(match[1]);
  } catch {
    return null;
  }
}

function itemIdFromPath(pathname: string): string | null {
  const match = pathname.match(/^\/api\/items\/([^/]+)$/);
  if (!match || match[1] === "counts") return null;
  try {
    return decodeURIComponent(match[1]);
  } catch {
    return null;
  }
}

type ItemMutation = "status" | "tags" | "tags/remove" | "notes" | "collections" | "collections/remove";

function itemMutationFromPath(pathname: string): { id: string; action: ItemMutation } | null {
  const match = pathname.match(
    /^\/api\/items\/([^/]+)\/(status|notes|tags\/remove|tags|collections\/remove|collections)$/,
  );
  if (!match) return null;
  try {
    return { id: decodeURIComponent(match[1]), action: match[2] as ItemMutation };
  } catch {
    return null;
  }
}

function readingDocumentIdFromPath(pathname: string): string | null {
  const match = pathname.match(/^\/api\/reading\/([^/]+)$/);
  if (!match || match[1] === "undo-remove") return null;
  try {
    return decodeURIComponent(match[1]);
  } catch {
    return null;
  }
}

type ReadingAction = "retry" | "progress" | "remove";

function readingActionFromPath(pathname: string): { id: string; action: ReadingAction } | null {
  const match = pathname.match(/^\/api\/reading\/([^/]+)\/(retry|progress|remove)$/);
  if (!match) return null;
  try {
    return { id: decodeURIComponent(match[1]), action: match[2] as ReadingAction };
  } catch {
    return null;
  }
}

function isReadingPath(method: string, pathname: string): boolean {
  if (pathname === "/api/reading") return method === "GET";
  if (pathname === "/api/reading/undo-remove") return method === "POST";
  if (method === "GET" && readingDocumentIdFromPath(pathname) !== null) return true;
  return method === "POST" && readingActionFromPath(pathname) !== null;
}

function parseReadingQuery(url: URL): ReadingListQuery {
  const viewRaw = url.searchParams.get("view");
  const sortRaw = url.searchParams.get("sort");
  const view: ReadingView | undefined = viewRaw === "finished" || viewRaw === "queue" ? viewRaw : undefined;
  const sort: ReadingSort | undefined =
    sortRaw === "recent" ||
    sortRaw === "oldest" ||
    sortRaw === "shortest" ||
    sortRaw === "longest" ||
    sortRaw === "publication"
      ? sortRaw
      : undefined;
  const limitRaw = url.searchParams.get("limit");
  const limit = limitRaw ? Number(limitRaw) : undefined;
  const kind = url.searchParams.get("kind") ?? undefined;
  const source = url.searchParams.get("source") ?? undefined;
  const q = url.searchParams.get("q") ?? undefined;
  const cursor = url.searchParams.get("cursor") ?? undefined;
  return {
    ...(view ? { view } : {}),
    ...(kind ? { kind } : {}),
    ...(source ? { source } : {}),
    ...(q ? { q } : {}),
    ...(sort ? { sort } : {}),
    ...(cursor ? { cursor } : {}),
    ...(Number.isFinite(limit) ? { limit } : {}),
  };
}

function parseAgentReadingQuery(url: URL): ReadingListQuery {
  const limitRaw = url.searchParams.get("limit");
  return {
    view: (url.searchParams.get("view") ?? undefined) as ReadingView | undefined,
    kind: url.searchParams.get("kind") ?? undefined,
    source: url.searchParams.get("source") ?? undefined,
    q: url.searchParams.get("q") ?? undefined,
    sort: (url.searchParams.get("sort") ?? undefined) as ReadingSort | undefined,
    cursor: url.searchParams.get("cursor") ?? undefined,
    limit: limitRaw === null ? undefined : Number(limitRaw),
  };
}

function isKitchenPath(pathname: string): boolean {
  return pathname === "/api/kitchen" || pathname.startsWith("/api/kitchen/");
}

function isAtlasPath(pathname: string): boolean {
  return pathname === "/api/atlas" || pathname.startsWith("/api/atlas/");
}

function isTripsPath(pathname: string): boolean {
  return pathname === "/api/trips" || pathname.startsWith("/api/trips/");
}

function isSourcesPath(method: string, pathname: string): boolean {
  if (pathname === "/api/sources") return method === "GET";
  if (pathname === "/api/extension/pair" || pathname === "/api/import/jsonl") return method === "POST";
  return method === "POST" && /^\/api\/sources\/[^/]+\/(connect|refresh|resume|cancel|disconnect)$/.test(pathname);
}

function isCapturePath(pathname: string): boolean {
  return pathname.startsWith("/capture/v1/");
}

function isDeskPath(method: string, pathname: string): boolean {
  if (
    method === "POST" &&
    (pathname === "/api/intake" ||
      pathname === "/api/intake/preview" ||
      pathname === "/api/intake/drafts/prepare" ||
      pathname === "/api/intake/drafts/save" ||
      pathname === "/api/intake/tags" ||
      pathname === "/api/intake/batch" ||
      pathname === "/api/collections" ||
      summaryProseFromPath(pathname) !== null)
  ) {
    return true;
  }
  if (
    method === "GET" &&
    (pathname === "/api/items" ||
      pathname === "/api/items/counts" ||
      pathname === "/api/collections" ||
      pathname === "/api/intake/context" ||
      pathname === "/api/intake/search" ||
      pathname === "/api/link-preview" ||
      pathname === "/api/frame-check" ||
      summaryScopeFromPath(pathname) !== null)
  ) {
    return true;
  }
  if (method === "GET" && itemIdFromPath(pathname) !== null) return true;
  return method === "POST" && itemMutationFromPath(pathname) !== null;
}

function summaryScopeFromPath(pathname: string): { scope: SummaryScope; ref: string } | null {
  const match = pathname.match(/^\/api\/summaries\/([^/]+)\/([^/]+)$/);
  if (!match) return null;
  const scope = decodeURIComponent(match[1]) as SummaryScope;
  if (scope !== "day" && scope !== "collection" && scope !== "selection" && scope !== "item") return null;
  try {
    return { scope, ref: decodeURIComponent(match[2]) };
  } catch {
    return null;
  }
}

function summaryProseFromPath(pathname: string): { scope: SummaryScope; ref: string } | null {
  const match = pathname.match(/^\/api\/summaries\/([^/]+)\/([^/]+)\/prose$/);
  if (!match) return null;
  const scope = decodeURIComponent(match[1]) as SummaryScope;
  if (scope !== "day" && scope !== "collection" && scope !== "selection" && scope !== "item") return null;
  try {
    return { scope, ref: decodeURIComponent(match[2]) };
  } catch {
    return null;
  }
}

function isCapabilitiesPath(method: string, pathname: string): boolean {
  if (pathname === "/api/library-capabilities") return method === "GET" || method === "POST";
  return method === "POST" && /^\/api\/library-capabilities\/[^/]+\/revoke$/.test(pathname);
}

function capabilityRevokeId(pathname: string): string | null {
  const match = pathname.match(/^\/api\/library-capabilities\/([^/]+)\/revoke$/);
  if (!match) return null;
  try {
    return decodeURIComponent(match[1]);
  } catch {
    return null;
  }
}

function itemListFilter(url: URL): ItemListFilter {
  const source = url.searchParams.get("source") ?? undefined;
  const q = url.searchParams.get("q") ?? undefined;
  const collectionId = url.searchParams.get("collectionId") ?? undefined;
  const shelf = url.searchParams.get("shelf") ?? undefined;
  return {
    view: url.searchParams.get("view") === "inbox" ? "inbox" : "recent",
    ...(source ? { source } : {}),
    ...(q ? { q } : {}),
    ...(collectionId ? { collectionId } : {}),
    ...(shelf ? { shelf } : {}),
  };
}

function isMutation(method: string): boolean {
  return method !== "GET" && method !== "HEAD" && method !== "OPTIONS";
}

function bytesToBase64Url(bytes: ArrayBuffer): string {
  const bin = String.fromCharCode(...new Uint8Array(bytes));
  return btoa(bin).replaceAll("+", "-").replaceAll("/", "_").replaceAll("=", "");
}

async function hmac(secret: string, value: string): Promise<string> {
  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  );
  const sig = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(value));
  return bytesToBase64Url(sig);
}

export async function csrfToken(sessionId: string, secret: string): Promise<string> {
  if (!secret || !sessionId) return "";
  return hmac(secret, sessionId);
}

async function timingSafeEqual(a: string, b: string): Promise<boolean> {
  const encoder = new TextEncoder();
  const [left, right] = await Promise.all([
    crypto.subtle.digest("SHA-256", encoder.encode(a)),
    crypto.subtle.digest("SHA-256", encoder.encode(b)),
  ]);
  const leftBytes = new Uint8Array(left);
  const rightBytes = new Uint8Array(right);
  let difference = 0;
  for (let index = 0; index < leftBytes.length; index++) {
    difference |= leftBytes[index] ^ rightBytes[index];
  }
  return difference === 0;
}

async function validCsrf(sessionId: string, token: string | null, secret: string): Promise<boolean> {
  if (!token || !secret) return false;
  const expected = await csrfToken(sessionId, secret);
  return expected.length > 0 && (await timingSafeEqual(token, expected));
}

async function requireMutationProtection(
  request: Request,
  env: Env,
  sessionId: string,
): Promise<Response | null> {
  if (request.headers.get("origin") !== env.BETTER_AUTH_URL) {
    return json({ error: "Forbidden" }, 403);
  }
  const token = request.headers.get("x-csrf-token");
  if (!(await validCsrf(sessionId, token, env.CSRF_SECRET))) {
    return json({ error: "Forbidden" }, 403);
  }
  return null;
}

export function redact(value: string): string {
  return value
    .replace(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi, "[redacted]")
    .replace(/((?:set-)?cookie\s*[:=]\s*)[^;\n]+/gi, "$1[redacted]")
    .replace(
      /\b(better-auth\.session_token|access_token|refresh_token|id_token|authorization|code|token)=([^&\s;]+)/gi,
      "$1=[redacted]",
    );
}

type LogLevel = "info" | "error";

export interface LogEvent {
  level: LogLevel;
  event: string;
  requestId: string;
  method: string;
  path: string;
  status: number;
  detail?: string;
  timestamp?: string;
}

export function logEvent(
  input: LogEvent,
  emit?: (line: string) => void,
): void {
  const record = {
    timestamp: input.timestamp ?? new Date().toISOString(),
    level: input.level,
    event: redact(input.event),
    requestId: redact(input.requestId),
    method: redact(input.method),
    path: redact(input.path.split("?", 1)[0]),
    status: input.status,
    ...(input.detail ? { detail: redact(input.detail) } : {}),
  };
  const line = JSON.stringify(record);
  if (emit) emit(line);
  else if (input.level === "error") console.error(line);
  else console.log(line);
}

export function mayLogRequest(request: Request, url = new URL(request.url)): boolean {
  return (
    url.search.length === 0 &&
    !request.headers.has("cookie") &&
    !request.headers.has("authorization")
  );
}

/** Public share tokens are credentials for the public page; they never go to
 * logs. The same empty 404 answers unknown and revoked tokens either way. */
export function requestLogPath(url: URL): string {
  return url.pathname.startsWith("/s/") ? "/s/[redacted]" : url.pathname;
}

function clientRateLimitKey(request: Request, scope: string): string {
  const client = request.headers.get("cf-connecting-ip") ?? "unknown";
  return `${scope}:${client}`;
}

async function enforceRateLimit(
  request: Request,
  limiter: RateLimit,
  scope: string,
): Promise<Response | null> {
  const outcome = await limiter.limit({ key: clientRateLimitKey(request, scope) });
  if (outcome.success) return null;
  return json(
    { error: "Too many requests" },
    429,
    { "retry-after": "60" },
  );
}

function authRateLimitScope(request: Request, pathname: string): string | null {
  if (request.method === "POST" && pathname === "/api/auth/sign-in/social") return "sign-in";
  if (pathname === "/api/auth/callback/google") return "google-callback";
  return null;
}

async function rejectedSessionResponse(
  request: Request,
  env: Env,
  response: Response,
): Promise<Response> {
  const limited = await enforceRateLimit(request, env.REJECTED_SESSION_RATE_LIMITER, "private-rejection");
  return limited ?? response;
}

export function applySecurityHeaders(response: Response, requestUrl: URL): Response {
  const headers = new Headers(response.headers);
  const hashedAsset = response.ok && requestUrl.pathname.startsWith("/assets/");
  headers.set("cache-control", hashedAsset ? "public, max-age=31536000, immutable" : "no-store");
  headers.set(
    "content-security-policy",
    "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' https: data:; base-uri 'none'; form-action 'self'; frame-ancestors 'none'",
  );
  headers.set("permissions-policy", "camera=(), geolocation=(), microphone=()");
  headers.set("referrer-policy", "no-referrer");
  headers.set("x-content-type-options", "nosniff");
  headers.set("x-frame-options", "DENY");
  if (requestUrl.protocol === "https:") {
    headers.set("strict-transport-security", "max-age=31536000; includeSubDomains");
  } else {
    headers.delete("strict-transport-security");
  }
  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}

function json(value: unknown, status = 200, headers?: HeadersInit): Response {
  const responseHeaders = new Headers(headers);
  responseHeaders.set("cache-control", "no-store");
  return Response.json(value, {
    status,
    headers: responseHeaders,
  });
}

async function readJson(request: Request): Promise<unknown> {
  const text = await request.text();
  if (!text) return {};
  try {
    return JSON.parse(text) as unknown;
  } catch {
    throw new RejectedPayload("invalid JSON");
  }
}

function scheduleReadingDrain(ctx: ExecutionContext, db: D1Database, libraryId?: string): void {
  ctx.waitUntil(drainReading(db, libraryId, 2));
}

async function drainCreatedIntake(
  ctx: ExecutionContext,
  db: D1Database,
  libraryId: string,
  drafts: { outcome: string }[],
): Promise<void> {
  if (drafts.some((draft) => draft.outcome === "created")) scheduleReadingDrain(ctx, db, libraryId);
}

function mcpUrl(env: Env): { origin: string; url: string } {
  return { origin: env.BETTER_AUTH_URL, url: `${env.BETTER_AUTH_URL}/mcp` };
}

async function withIdentity(
  request: Request,
  env: Env,
  auth: ReturnType<typeof createAuth>,
  handler: (identity: RequestIdentity, library: LibraryRow) => Promise<Response>,
): Promise<Response> {
  const session = await auth.api.getSession({ headers: request.headers });
  const resolved = await resolveIdentity(env, session);
  if (!resolved.ok) {
    return rejectedSessionResponse(request, env, json({ error: resolved.error }, resolved.status));
  }
  if (isMutation(request.method)) {
    const blocked = await requireMutationProtection(request, env, resolved.identity.sessionId);
    if (blocked) return blocked;
  }
  try {
    return await handler(resolved.identity, resolved.library);
  } catch (error) {
    if (error instanceof RejectedPayload) return json({ error: error.message }, 400);
    if (error instanceof MissingResource) return json({ error: "Not found" }, 404);
    if (error instanceof ExtensionRequired || error instanceof CaptureConflict) {
      return json({ error: error.message }, 409);
    }
    if (error instanceof CaptureAuthorizationError) return json({ error: error.message }, error.statusCode);
    if (error instanceof KitchenUnavailable) return json({ error: error.message }, 503);
    if (error instanceof ReviewIntentError) return json({ error: error.message }, 403);
    if (
      error instanceof KitchenConflict ||
      error instanceof AtlasConflict ||
      error instanceof TripConflict
    ) {
      return json({ error: error.message }, 409);
    }
    throw error;
  }
}

async function routeMcp(request: Request, env: Env): Promise<Response> {
  if (request.method === "GET") {
    return new Response(null, { status: 405, headers: { allow: "POST", "cache-control": "no-store" } });
  }
  if (request.method !== "POST") return json({ error: "Not found" }, 404);
  try {
    const token = bearer(request);
    const capability = token ? await lookupLibraryCapability(env.DB, token) : null;
    if (!capability || !libraryCapabilityUsable(capability)) {
      return json({ error: "unauthorized" }, 401);
    }
    const handled = await handleLibraryMcp(env.DB, capability, await readJson(request));
    if (handled.status === 202) return new Response(null, { status: 202, headers: { "cache-control": "no-store" } });
    return json(handled.body, handled.status);
  } catch (error) {
    if (error instanceof RejectedPayload) return json({ error: error.message }, 400);
    throw error;
  }
}

async function routeCapabilities(
  request: Request,
  env: Env,
  identity: RequestIdentity,
): Promise<Response | null> {
  const url = new URL(request.url);
  const db = env.DB;
  const libraryId = identity.libraryId;
  const links = mcpUrl(env);
  if (request.method === "GET" && url.pathname === "/api/library-capabilities") {
    return json({
      capabilities: await listLibraryCapabilities(db, libraryId),
      origin: links.origin,
      url: links.url,
    });
  }
  if (request.method === "POST" && url.pathname === "/api/library-capabilities") {
    const body = rec(await readJson(request));
    const issued = await issueLibraryCapability(db, {
      libraryId,
      scope: body.scope,
      label: body.label,
    });
    return json({
      token: issued.token,
      origin: links.origin,
      url: links.url,
      capability: issued.capability,
    });
  }
  const id = capabilityRevokeId(url.pathname);
  if (request.method === "POST" && id) {
    if (!(await revokeLibraryCapability(db, libraryId, id))) return json({ error: "Not found" }, 404);
    return json({ revoked: true });
  }
  return null;
}

async function routeDesk(
  request: Request,
  env: Env,
  identity: RequestIdentity,
  ctx: ExecutionContext,
): Promise<Response | null> {
  const url = new URL(request.url);
  const db = env.DB;
  const libraryId = identity.libraryId;

  if (request.method === "POST" && url.pathname === "/api/intake") {
    const result = await commitIntake(db, libraryId, await readJson(request));
    const queued = await reconcileItem(db, libraryId, result.item.id);
    if (queued) scheduleReadingDrain(ctx, db, libraryId);
    return json(result);
  }
  if (request.method === "POST" && url.pathname === "/api/intake/preview") {
    return json(await previewIntake(db, libraryId, await readJson(request)));
  }
  if (request.method === "GET" && url.pathname === "/api/intake/context") {
    return json(await getIntakeContext(db, libraryId));
  }
  if (request.method === "GET" && url.pathname === "/api/intake/search") {
    const query: { url?: string; q?: string } = {};
    const itemUrl = url.searchParams.get("url");
    const q = url.searchParams.get("q");
    if (itemUrl) query.url = itemUrl;
    if (q) query.q = q;
    return json(await searchLibrary(db, libraryId, query));
  }
  if (request.method === "POST" && url.pathname === "/api/intake/drafts/prepare") {
    const drafts = await preparePresentedDrafts(db, libraryId, await readJson(request));
    return json({ drafts, context: await getIntakeContext(db, libraryId) });
  }
  if (request.method === "POST" && url.pathname === "/api/intake/drafts/save") {
    const result = await commitReviewedDrafts(db, libraryId, await readJson(request));
    await drainCreatedIntake(ctx, db, libraryId, result.drafts);
    return json(result);
  }
  if (request.method === "POST" && url.pathname === "/api/intake/tags") {
    return json(await createIntakeTag(db, libraryId, await readJson(request)));
  }
  if (request.method === "POST" && url.pathname === "/api/intake/batch") {
    const result = await commitIntakeBatch(db, libraryId, "agent", await readJson(request));
    await drainCreatedIntake(ctx, db, libraryId, result.drafts);
    return json(result);
  }
  if (request.method === "GET" && url.pathname === "/api/items") {
    const requested = Number(url.searchParams.get("limit") ?? 50);
    return json(
      await listItemsPage(db, libraryId, itemListFilter(url), {
        cursor: url.searchParams.get("cursor") ?? undefined,
        limit: Number.isFinite(requested) ? requested : 50,
      }),
    );
  }
  if (request.method === "GET" && url.pathname === "/api/items/counts") {
    return json({ counts: await itemCounts(db, libraryId, itemListFilter(url)) });
  }
  const itemId = itemIdFromPath(url.pathname);
  if (request.method === "GET" && itemId) {
    const item = await getLibraryItem(db, libraryId, itemId);
    if (!item) return json({ error: "Not found" }, 404);
    return json({ item });
  }
  if (request.method === "GET" && url.pathname === "/api/collections") {
    return json(await listLibraryOrg(db, libraryId));
  }
  if (request.method === "GET" && url.pathname === "/api/link-preview") {
    return json({ preview: await getLinkPreview(db, libraryId, url.searchParams.get("url") ?? "") });
  }
  if (request.method === "GET" && url.pathname === "/api/frame-check") {
    return json({ framed: await frameCheck(url.searchParams.get("url") ?? "") });
  }
  const summaryScope = summaryScopeFromPath(url.pathname);
  if (request.method === "GET" && summaryScope) {
    return json({
      snapshot: await buildSummary(db, libraryId, summaryScope.scope, summaryScope.ref),
      pi: { available: false, detail: proseUnavailableMessage() },
    });
  }
  const summaryProse = summaryProseFromPath(url.pathname);
  if (request.method === "POST" && summaryProse) {
    return json(
      {
        error: proseUnavailableMessage(),
        snapshot: await buildSummary(db, libraryId, summaryProse.scope, summaryProse.ref),
      },
      400,
    );
  }
  if (request.method === "POST" && url.pathname === "/api/collections") {
    return json(await createLibraryCollection(db, libraryId, await readJson(request)));
  }
  const mutation = itemMutationFromPath(url.pathname);
  if (request.method === "POST" && mutation) {
    const input = await readJson(request);
    if (mutation.action === "status") return json(await setItemStatus(db, libraryId, mutation.id, input));
    if (mutation.action === "tags") return json(await addItemTag(db, libraryId, mutation.id, input));
    if (mutation.action === "tags/remove") return json(await removeItemTag(db, libraryId, mutation.id, input));
    if (mutation.action === "notes") return json(await addItemNote(db, libraryId, mutation.id, input));
    if (mutation.action === "collections") return json(await addItemToCollection(db, libraryId, mutation.id, input));
    return json(await removeItemFromCollection(db, libraryId, mutation.id, input));
  }
  return null;
}

async function routeReading(
  request: Request,
  env: Env,
  identity: RequestIdentity,
  ctx: ExecutionContext,
): Promise<Response | null> {
  const url = new URL(request.url);
  const db = env.DB;
  const libraryId = identity.libraryId;

  if (request.method === "GET" && url.pathname === "/api/reading") {
    if (url.searchParams.get("audience") === "agent") {
      return json(await listReadingDocumentsForAgent(db, libraryId, parseAgentReadingQuery(url)));
    }
    return json(await listReadingDocuments(db, libraryId, parseReadingQuery(url)));
  }
  if (request.method === "POST" && url.pathname === "/api/reading/undo-remove") {
    const input = await readJson(request);
    const token = input && typeof input === "object" ? String((input as { token?: unknown }).token ?? "") : "";
    return json({ document: await undoRemoveReadingDocument(db, libraryId, token) });
  }
  const documentId = readingDocumentIdFromPath(url.pathname);
  if (request.method === "GET" && documentId) {
    if (url.searchParams.get("audience") === "agent") {
      return json({ document: await getAgentReadingDocument(db, libraryId, documentId) });
    }
    return json({ document: await getReadingDocument(db, libraryId, documentId) });
  }
  const action = readingActionFromPath(url.pathname);
  if (request.method === "POST" && action) {
    if (action.action === "retry") {
      await retryReadingDocument(db, libraryId, action.id);
      scheduleReadingDrain(ctx, db, libraryId);
      return json({ document: await getReadingDocument(db, libraryId, action.id) });
    }
    if (action.action === "progress") {
      return json({ progress: await updateReadingProgress(db, libraryId, action.id, (await readJson(request)) as object) });
    }
    return json(await removeReadingDocument(db, libraryId, action.id));
  }
  return null;
}

function rec(input: unknown): Record<string, unknown> {
  return input && typeof input === "object" && !Array.isArray(input) ? (input as Record<string, unknown>) : {};
}

async function routeKitchen(request: Request, env: Env, identity: RequestIdentity): Promise<Response | null> {
  const url = new URL(request.url);
  const db = env.DB;
  const libraryId = identity.libraryId;
  const pathname = url.pathname;

  if (request.method === "GET" && pathname === "/api/kitchen") {
    const limitRaw = url.searchParams.get("limit");
    const limit = limitRaw ? Number(limitRaw) : undefined;
    return json(
      await getKitchenIndex(db, libraryId, {
        q: url.searchParams.get("q") ?? undefined,
        source: url.searchParams.get("source") ?? undefined,
        cursor: url.searchParams.get("cursor") ?? undefined,
        limit: Number.isFinite(limit) ? limit : undefined,
      }),
    );
  }
  if (request.method === "GET" && pathname === "/api/kitchen/ai") {
    return json(kitchenAiStatus());
  }
  const kitchenItem = pathname.match(/^\/api\/kitchen\/items\/([^/]+)(?:\/(make-cookable|recipe\/remove|recipe|propose-recipe))?$/);
  if (kitchenItem) {
    const itemId = decodeURIComponent(kitchenItem[1]);
    const action = kitchenItem[2];
    if (request.method === "GET" && !action) {
      const item = await getKitchenItem(db, libraryId, itemId);
      if (!item) return json({ error: "Not found" }, 404);
      return json(item);
    }
    if (request.method === "POST" && action === "make-cookable") {
      const allowGenerate = rec(await readJson(request)).allowGenerate;
      if (typeof allowGenerate !== "boolean") throw new RejectedPayload("allowGenerate must be boolean");
      return json(await makeCookable(db, libraryId, itemId));
    }
    if (request.method === "POST" && action === "recipe") {
      const body = rec(await readJson(request));
      return json({
        document: await putRecipeDocument(
          db,
          libraryId,
          itemId,
          {
            expectedSourceRevision: typeof body.expectedSourceRevision === "string" ? body.expectedSourceRevision : "",
            status: body.status as "draft" | "reviewed",
            draft: body.draft,
          },
          "user",
        ),
      });
    }
    if (request.method === "POST" && action === "recipe/remove") {
      const removed = await removeRecipeDocument(db, libraryId, itemId);
      if (!removed) return json({ error: "Not found" }, 404);
      return json({ removed });
    }
    if (request.method === "POST" && action === "propose-recipe") {
      const body = rec(await readJson(request));
      const allowGenerate = body.allowGenerate ?? false;
      if (typeof allowGenerate !== "boolean") throw new RejectedPayload("allowGenerate must be boolean");
      return json({
        document: await putRecipeDocument(
          db,
          libraryId,
          itemId,
          {
            expectedSourceRevision: typeof body.expectedSourceRevision === "string" ? body.expectedSourceRevision : "",
            status: "draft",
            draft: body.draft,
            allowGenerate,
          },
          "agent",
        ),
      });
    }
  }
  if (request.method === "GET" && pathname === "/api/kitchen/tonight") return json(await getTonight(db, libraryId));
  if (request.method === "POST" && pathname === "/api/kitchen/tonight") {
    return json(await addTonight(db, libraryId, String(rec(await readJson(request)).itemId ?? "")));
  }
  if (request.method === "POST" && pathname === "/api/kitchen/tonight/reorder") {
    const entryIds = rec(await readJson(request)).entryIds;
    if (!Array.isArray(entryIds)) throw new RejectedPayload("entryIds must be an array");
    return json(await reorderTonight(db, libraryId, entryIds.map(String)));
  }
  if (request.method === "GET" && pathname === "/api/kitchen/tonight/state") return json(await getTonightView(db, libraryId));
  if (request.method === "POST" && pathname === "/api/kitchen/tonight/apply") {
    return json(await applyTonightChanges(db, libraryId, await readJson(request)));
  }
  if (request.method === "POST" && pathname === "/api/kitchen/tonight/clear") {
    return json({ removed: await clearTonight(db, libraryId) });
  }
  const tonightRemove = pathname.match(/^\/api\/kitchen\/tonight\/([^/]+)\/remove$/);
  if (request.method === "POST" && tonightRemove) {
    const removed = await removeTonight(db, libraryId, decodeURIComponent(tonightRemove[1]));
    if (!removed) return json({ error: "Not found" }, 404);
    return json({ removed });
  }
  return null;
}

async function routeAtlas(request: Request, env: Env, identity: RequestIdentity): Promise<Response | null> {
  const url = new URL(request.url);
  const db = env.DB;
  const libraryId = identity.libraryId;
  const pathname = url.pathname;

  if (request.method === "GET" && pathname === "/api/atlas") return json(await getAtlasProjection(db, libraryId));
  if (request.method === "GET" && pathname === "/api/atlas/places") {
    return json({ places: await searchPlaces(db, libraryId, url.searchParams.get("q") ?? "") });
  }
  if (request.method === "POST" && pathname === "/api/atlas/home") {
    const body = rec(await readJson(request));
    const place = body.placeId
      ? await setHomeBase(db, libraryId, String(body.placeId))
      : body.name
        ? await setHomeBase(
            db,
            libraryId,
            (
              await createPlace(db, libraryId, {
                name: String(body.name),
                kind: body.kind ? String(body.kind) : undefined,
                parentId: body.parentId ? String(body.parentId) : null,
              })
            ).id,
          )
        : await setHomeBase(db, libraryId, null);
    return json({ home: place, atlas: await getAtlasProjection(db, libraryId) });
  }
  const itemAction = pathname.match(/^\/api\/atlas\/items\/([^/]+)\/(accept|place|multiple|not-atlas|leave|change)$/);
  if (request.method === "POST" && itemAction) {
    const itemId = decodeURIComponent(itemAction[1]);
    const action = itemAction[2];
    const body = rec(await readJson(request));
    const expectedVersion = Number(body.expectedVersion);
    let assignment;
    if (action === "accept") assignment = await acceptSuggestion(db, libraryId, itemId, Number(body.index), expectedVersion);
    else if (action === "place") {
      assignment = await setExactPlace(
        db,
        libraryId,
        itemId,
        {
          placeId: body.placeId ? String(body.placeId) : undefined,
          name: body.name ? String(body.name) : undefined,
          kind: body.kind ? String(body.kind) : undefined,
          parentId: body.parentId == null ? (body.parentId as null) : body.parentId ? String(body.parentId) : undefined,
        },
        expectedVersion,
      );
    } else if (action === "multiple") assignment = await markMultiple(db, libraryId, itemId, expectedVersion);
    else if (action === "not-atlas") assignment = await markNotAtlas(db, libraryId, itemId, expectedVersion);
    else if (action === "leave") assignment = await leaveUnresolved(db, libraryId, itemId, expectedVersion);
    else assignment = await changePlace(db, libraryId, itemId, String(body.placeId ?? ""), expectedVersion);
    return json({ assignment, atlas: await getAtlasProjection(db, libraryId) });
  }
  return null;
}

async function missingTrip(): Promise<Response> {
  return json({ error: "Not found" }, 404);
}

async function routeTrips(request: Request, env: Env, identity: RequestIdentity): Promise<Response | null> {
  const url = new URL(request.url);
  const db = env.DB;
  const libraryId = identity.libraryId;
  const pathname = url.pathname;

  if (request.method === "GET" && pathname === "/api/trips") return json({ trips: await listTrips(db, libraryId) });
  if (request.method === "POST" && pathname === "/api/trips") {
    return json({ trip: await createTrip(db, libraryId, await readJson(request)) });
  }
  if (request.method === "GET" && pathname === "/api/trips/sources") {
    return json(await searchTripSources(db, libraryId, url.searchParams.get("q") ?? ""));
  }
  const tripMatch = pathname.match(/^\/api\/trips\/([^/]+)(?:\/(.*))?$/);
  if (!tripMatch || tripMatch[1] === "sources") return null;
  const tripId = decodeURIComponent(tripMatch[1]);
  const rest = tripMatch[2] ?? "";
  if (request.method === "GET" && rest === "") {
    const trip = await getTrip(db, libraryId, tripId);
    if (!trip) return missingTrip();
    return json({ trip });
  }
  if (request.method === "GET" && rest === "history") {
    const history = await getTripHistory(db, libraryId, tripId);
    if (!history) return missingTrip();
    return json(history);
  }
  if (request.method === "GET" && rest === "share") {
    const trip = await getTrip(db, libraryId, tripId);
    if (!trip) return missingTrip();
    return json({ shared: await getShareState(db, libraryId, trip.id) });
  }
  if (request.method !== "POST") return null;
  const body = await readJson(request);
  if (rest === "update") {
    const trip = await updateTripSetup(db, libraryId, tripId, body);
    return trip ? json({ trip }) : missingTrip();
  }
  if (rest === "changes") {
    const result = await applyTripChanges(db, libraryId, tripId, body, "user");
    return result ? json(result) : missingTrip();
  }
  if (rest === "agent/changes") {
    const result = await applyTripChanges(db, libraryId, tripId, body, "agent");
    return result ? json(result) : missingTrip();
  }
  if (rest === "review-intent") {
    const armed = await armReviewIntent(db, libraryId, identity.sessionId, tripId);
    return armed ? json({ ok: true, revision: armed.revision }) : missingTrip();
  }
  if (rest === "agent/review") {
    const result = await recordAgentReview(db, libraryId, identity.sessionId, tripId, body);
    return result ? json(result) : missingTrip();
  }
  if (rest === "undo") {
    const result = await undoTripChanges(db, libraryId, tripId, body, "user");
    return result ? json(result) : missingTrip();
  }
  if (rest === "redo") {
    const result = await redoTripChanges(db, libraryId, tripId, body, "user");
    return result ? json(result) : missingTrip();
  }
  if (rest === "rename") {
    const trip = await renameTrip(db, libraryId, tripId, body);
    return trip ? json({ trip }) : missingTrip();
  }
  if (rest === "duplicate") {
    const trip = await duplicateTrip(db, libraryId, tripId, body);
    return trip ? json({ trip }) : missingTrip();
  }
  if (rest === "archive") {
    const trip = await archiveTrip(db, libraryId, tripId, body);
    return trip ? json({ trip }) : missingTrip();
  }
  if (rest === "restore") {
    const trip = await restoreTrip(db, libraryId, tripId, body);
    return trip ? json({ trip }) : missingTrip();
  }
  if (rest === "delete") {
    const deleted = await deleteTrip(db, libraryId, tripId, body);
    return deleted ? json({ deleted: true }) : missingTrip();
  }
  if (rest === "share/preview") {
    const preview = await previewShareSnapshot(db, libraryId, tripId);
    return preview ? json(preview) : missingTrip();
  }
  if (rest === "share/publish") {
    const result = await publishShareSnapshot(db, libraryId, tripId, body);
    return result ? json(result) : missingTrip();
  }
  if (rest === "share/revoke") {
    const revoked = await revokeShareSnapshot(db, libraryId, tripId, body);
    return revoked === null ? missingTrip() : json({ revoked });
  }
  const advisory = rest.match(/^advisories\/([^/]+)\/dismiss$/);
  if (advisory) {
    const trip = await dismissTripAdvisory(db, libraryId, tripId, decodeURIComponent(advisory[1]), body);
    return trip ? json({ trip }) : missingTrip();
  }
  const inference = rest.match(/^inferences\/([^/]+)\/remove$/);
  if (inference) {
    const trip = await removeTripInference(db, libraryId, tripId, decodeURIComponent(inference[1]), body);
    return trip ? json({ trip }) : missingTrip();
  }
  return null;
}

function bearer(request: Request): string {
  const header = request.headers.get("authorization") ?? "";
  const match = /^Bearer\s+(\S+)/i.exec(header);
  return match?.[1] ?? "";
}

async function requireCaptureToken(request: Request, env: Env): Promise<CaptureToken | Response> {
  const offered = bearer(request);
  if (!offered) return json({ error: "missing token" }, 401);
  const token = await lookupToken(env.DB, offered);
  if (!token || token.revokedAt) return json({ error: "invalid token" }, 401);
  return token;
}

async function routeSources(request: Request, env: Env, identity: RequestIdentity): Promise<Response | null> {
  const url = new URL(request.url);
  const db = env.DB;
  const libraryId = identity.libraryId;
  const pathname = url.pathname;

  if (request.method === "GET" && pathname === "/api/sources") {
    return json(await sourcesOverview(db, libraryId));
  }
  if (request.method === "POST" && pathname === "/api/extension/pair") {
    return json(await pairExtension(db, libraryId, env.BETTER_AUTH_URL));
  }
  if (request.method === "POST" && pathname === "/api/import/jsonl") {
    const body = rec(await readJson(request));
    const text = String(body.text ?? "");
    const dryRun = Boolean(body.dryRun);
    return json(await importJsonl(db, libraryId, text, { dryRun }));
  }
  const sourceAction = pathname.match(/^\/api\/sources\/([^/]+)\/(connect|refresh|resume|cancel|disconnect)$/);
  if (request.method === "POST" && sourceAction) {
    const source = decodeURIComponent(sourceAction[1]);
    const action = sourceAction[2];
    const body = rec(await readJson(request));
    const accountId = typeof body.accountId === "string" ? body.accountId : undefined;
    if (action === "connect" || action === "refresh" || action === "resume") {
      return json(await beginCapture(db, libraryId, source, accountId));
    }
    if (!accountId) throw new RejectedPayload("accountId required");
    if (action === "cancel") {
      await cancelCapture(db, libraryId, source, accountId);
      return json({ ok: true });
    }
    await disconnectSource(db, libraryId, source, accountId);
    return json({ ok: true });
  }
  return null;
}

async function routeCapture(
  request: Request,
  env: Env,
  ctx: ExecutionContext,
): Promise<Response | null> {
  const url = new URL(request.url);
  const pathname = url.pathname;
  if (!isCapturePath(pathname)) return null;
  const db = env.DB;

  try {
    if (request.method === "POST" && pathname === "/capture/v1/hello") {
      const body = rec(await readJson(request));
      const offered = String(body.token ?? bearer(request) ?? "");
      const existing = offered ? await lookupToken(db, offered) : null;
      if (existing && !existing.revokedAt && existing.source === "*") {
        await heartbeat(db, existing.libraryId);
        return json({ token: offered, origin: env.BETTER_AUTH_URL });
      }
      return json({ error: "invalid token" }, 401);
    }

    if (request.method === "GET" && pathname === "/capture/v1/jobs/wait") {
      const auth = await requireCaptureToken(request, env);
      if (auth instanceof Response) return auth;
      const job = await waitJob(db, auth);
      if (!job) return new Response(null, { status: 204, headers: { "cache-control": "no-store" } });
      return json(jobDeliveryView(job));
    }

    const jobMatch = pathname.match(/^\/capture\/v1\/jobs\/([^/]+)(?:\/(progress|finish))?$/);
    if (jobMatch) {
      const jobId = decodeURIComponent(jobMatch[1]);
      const action = jobMatch[2];
      const auth = await requireCaptureToken(request, env);
      if (auth instanceof Response) return auth;
      const job = await getAccessibleJob(db, auth, jobId);
      if (request.method === "GET" && !action) {
        await touchJobLease(db, job);
        return json(jobStatusView(job));
      }
      if (request.method === "POST" && action === "progress") {
        const body = rec(await readJson(request));
        return json(
          await setJobProgress(db, job, {
            phase: String(body.phase ?? "capturing"),
            message: String(body.message ?? ""),
            seen: typeof body.seen === "number" ? body.seen : undefined,
            upserted: typeof body.upserted === "number" ? body.upserted : undefined,
          }),
        );
      }
      if (request.method === "POST" && action === "finish") {
        const body = rec(await readJson(request));
        await finishCaptureJob(db, job, {
          error: body.error ? String(body.error) : undefined,
          message: body.message ? String(body.message) : undefined,
          seen: typeof body.seen === "number" ? body.seen : undefined,
          upserted: typeof body.upserted === "number" ? body.upserted : undefined,
        });
        return json({ ok: true });
      }
    }

    if (request.method === "GET" && pathname === "/capture/v1/known") {
      const auth = await requireCaptureToken(request, env);
      if (auth instanceof Response) return auth;
      return json({ done: await knownCompleteIds(db, auth, url.searchParams.get("source")) });
    }

    if (request.method === "POST" && pathname === "/capture/v1/sessions") {
      const auth = await requireCaptureToken(request, env);
      if (auth instanceof Response) return auth;
      const grantJob = await jobForTokenId(db, auth.id);
      if (grantJob?.status === "cancelled") return json({ error: "job is cancelled" }, 403);
      const session = parseSession(await readJson(request));
      const started = await startSession(db, auth, session);
      if (auth.sourceAccountId && started.sourceAccountId !== auth.sourceAccountId && session.source) {
        await retargetJobs(db, String(session.source), auth.sourceAccountId, started.sourceAccountId);
      }
      return json(started);
    }

    if (request.method === "POST" && pathname === "/capture/v1/batches") {
      const auth = await requireCaptureToken(request, env);
      if (auth instanceof Response) return auth;
      const result = await ingestBatch(db, parseBatch(await readJson(request)), { token: auth });
      // Reading extract runs on the minute cron. Do not waitUntil-fetch here:
      // a hung X/Instagram fetch would stall the capture request and freeze the extension.
      return json(result);
    }

    if (request.method === "POST" && pathname === "/capture/v1/finish") {
      const auth = await requireCaptureToken(request, env);
      if (auth instanceof Response) return auth;
      const result = await finishSession(db, parseFinish(await readJson(request)), auth);
      return json(result);
    }

    return json({ error: "Not found" }, 404);
  } catch (error) {
    if (error instanceof RejectedPayload) return json({ error: error.message }, 400);
    if (error instanceof CaptureAuthorizationError) return json({ error: error.message }, error.statusCode);
    throw error;
  }
}

function expiresAt(value: Date | string): string {
  return value instanceof Date ? value.toISOString() : String(value);
}

async function route(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
  const url = new URL(request.url);
  const auth = createAuth(env);

  if (url.pathname.startsWith("/api/auth/")) {
    const scope = authRateLimitScope(request, url.pathname);
    if (scope) {
      const limited = await enforceRateLimit(request, env.AUTH_RATE_LIMITER, scope);
      if (limited) return limited;
    }
    return auth.handler(request);
  }

  if (url.pathname === "/mcp") {
    return routeMcp(request, env);
  }

  // Public Share Snapshot page. Deliberately outside /api/ and before auth:
  // no session, no cookie, no account. Revoked and unknown tokens get the
  // same empty 404 with no itinerary payload.
  if (request.method === "GET" && url.pathname.startsWith("/s/")) {
    let token = url.pathname.slice(3);
    try {
      token = decodeURIComponent(token);
    } catch {
      // Keep the raw slice; the lookup treats it as any other miss.
    }
    const shared = await findSharedSnapshot(env.DB, token);
    if (!shared) {
      return new Response(
        `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Link unavailable</title></head><body style="font-family:system-ui,sans-serif;color:#6b7176;background:#f1f2ef;margin:0"><main style="max-width:560px;margin:0 auto;padding:60px 20px"><p>This link is no longer available.</p></main></body></html>`,
        { status: 404, headers: { "content-type": "text/html; charset=utf-8" } },
      );
    }
    return new Response(renderShareHtml(shared.snapshot, shared.updatedAt), {
      status: 200,
      headers: { "content-type": "text/html; charset=utf-8" },
    });
  }

  if (isCapturePath(url.pathname)) {
    const response = await routeCapture(request, env, ctx);
    return response ?? json({ error: "Not found" }, 404);
  }

  if (request.method === "GET" && url.pathname === "/api/health") {
    return json({ ok: true });
  }

  if (request.method === "GET" && url.pathname === "/api/session") {
    const session = await auth.api.getSession({ headers: request.headers });
    if (!session) {
      return rejectedSessionResponse(request, env, json({ error: "Unauthorized" }, 401));
    }
    const access = await ensureAccess(env, session.user);
    if (access !== "active") {
      return rejectedSessionResponse(request, env, json({ error: "Forbidden" }, 403));
    }
    const library = await ensureLibrary(env, session.user.id, session.user.name);
    const token = await csrfToken(session.session.id, env.CSRF_SECRET);
    return json({
      user: {
        id: session.user.id,
        name: session.user.name,
        email: session.user.email,
        image: session.user.image ?? null,
      },
      session: {
        expiresAt: expiresAt(session.session.expiresAt),
      },
      library: {
        id: library.id,
        name: library.name,
        role: library.role,
      },
      csrfToken: token,
    });
  }

  const libraryId = libraryIdFromPath(url.pathname);
  if (libraryId && (request.method === "GET" || request.method === "POST")) {
    return withIdentity(request, env, auth, async (identity, library) => {
      if (libraryId !== identity.libraryId) return json({ error: "Not found" }, 404);
      return json({
        id: library.id,
        name: library.name,
        role: library.role,
      });
    });
  }

  if (isSourcesPath(request.method, url.pathname)) {
    return withIdentity(request, env, auth, async (identity) => {
      const response = await routeSources(request, env, identity);
      return response ?? json({ error: "Not found" }, 404);
    });
  }

  if (isDeskPath(request.method, url.pathname)) {
    return withIdentity(request, env, auth, async (identity) => {
      const response = await routeDesk(request, env, identity, ctx);
      return response ?? json({ error: "Not found" }, 404);
    });
  }

  if (isCapabilitiesPath(request.method, url.pathname)) {
    return withIdentity(request, env, auth, async (identity) => {
      const response = await routeCapabilities(request, env, identity);
      return response ?? json({ error: "Not found" }, 404);
    });
  }

  if (isReadingPath(request.method, url.pathname)) {
    return withIdentity(request, env, auth, async (identity) => {
      const response = await routeReading(request, env, identity, ctx);
      return response ?? json({ error: "Not found" }, 404);
    });
  }

  if (isKitchenPath(url.pathname)) {
    return withIdentity(request, env, auth, async (identity) => {
      const response = await routeKitchen(request, env, identity);
      return response ?? json({ error: "Not found" }, 404);
    });
  }

  if (isAtlasPath(url.pathname)) {
    return withIdentity(request, env, auth, async (identity) => {
      const response = await routeAtlas(request, env, identity);
      return response ?? json({ error: "Not found" }, 404);
    });
  }

  if (isTripsPath(url.pathname)) {
    return withIdentity(request, env, auth, async (identity) => {
      const response = await routeTrips(request, env, identity);
      return response ?? json({ error: "Not found" }, 404);
    });
  }

  if (url.pathname.startsWith("/api/")) {
    return json({ error: "Not found" }, 404);
  }
  return env.ASSETS.fetch(request);
}

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);
    const requestId = request.headers.get("cf-ray") ?? crypto.randomUUID();
    try {
      const response = applySecurityHeaders(await route(request, env, ctx), url);
      if (mayLogRequest(request, url)) {
        logEvent({
          level: "info",
          event: "request.complete",
          requestId,
          method: request.method,
          path: requestLogPath(url),
          status: response.status,
        });
      }
      return response;
    } catch {
      const response = applySecurityHeaders(json({ error: "Internal server error" }, 500), url);
      if (mayLogRequest(request, url)) {
        logEvent({
          level: "error",
          event: "request.failed",
          requestId,
          method: request.method,
          path: requestLogPath(url),
          status: 500,
          detail: "Unhandled Worker error",
        });
      }
      return response;
    }
  },
  async scheduled(_controller: ScheduledController, env: Env, ctx: ExecutionContext): Promise<void> {
    ctx.waitUntil(drainReading(env.DB));
  },
} satisfies ExportedHandler<Env>;
